@startuml RenovIUTApp

skinparam style strictuml
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
hide enum methods

class RenovIUTApp 
{
    + {static} main( args:String[] )
}

package models 
{
    package building
    {
        abstract class Building 
        {
            + _age : Integer
            + getCode() : String
        }

        class IT
        {
            + <<create>>IT()
        }

        class Communication
        {
            + <<create>>Communication()
        }

        class Marketing
        {
            + <<create>>Marketing()
        }

        class Chemistry
        {
            + <<create>>Chemistry()
        }

        class Engineering
        {
            + <<create>>Engineering()
        }
    }

    class Student 
    {
        + «Create» Student(dept : String)
        + add_student(dept : String)
        + get_id() : Integer
        + get_year() : Integer
        + get_dept() : String
        + get_mood() : Real
        + get_lvl() : Real
        + set_year(year : Integer)
        + set_mood(coeff : Real)
        + set_level(coeff : Real)
    }


    class Teacher
    {
        + «Create» Teacher(dept : String)
        + add_teacher(dept : String)
        + get_id() : Integer
        + get_dept() : String
        + get_mood() : Real
        + set_mood(coeff : Real)
    }

    class Fund
    {
        + «Create» Fund(source : String, amount : Real, destination : String?)
        + add_fund(source : String, amount : Real, destination : String?)
        + get_id() : Integer
        + get_source() : String
        + get_amount() : Real
        + get_destination() : String?
        + set_destination() : String
    }

    class StudentTableSQL
    {
        + _id : Integer <<PK>>
        + _year : Integer [1..3]
        + _dept : String
        + _mood : Real [0, 1]
        + _lvl : Real [0, 1]
    }

    class TeacherTableSQL
    {
        + _id : Integer <<PK>>
        + _dept : String
        + _mood : Real [0, 1]
    }

    class FundTableSQL
    {
        + _id : Integer <<PK>>
        + _amount : Real
        + _source : String
        + _destination : String?
    }
}

package controllers {
    package school {
        class Study
        {
            + rm_student_by_id(i : Integer)
            + rm_student_by_dept(dept : String, nb : Integer)
            + populate_year()
            + populate_promo()
            + compute_nb_by_dept(dept : String) : Integer
            + avg_mood_by_dept(dept : String) : Real
            + compute_nb() : Integer
            + avg_mood() : Real
            + evaluate()
            + success_rate_by_dept(dept : String) : Real
            + success_rate() : Real
        }

        class Teaching
        {
            + rm_teacher_by_id(i : Integer)
            + rm_teacher_by_dept(dept : String, nb : Integer)
            + compute_nb_by_dept(dept : String) : Integer
            + avg_mood_by_dept(dept : String) : Real
            + compute_nb() : Integer
            + avg_mood() : Real
            + populate()
        }
    }
    package management {
        class Financing
        {
            + rm_fund_by_id(i : Integer)
            + rm_fund_by_source(source : String)
            + compute_amount_by_dept(dept : String) : Real
            + compute_total() : Real
        }

        abstract class Renovation {

        }

        class Planned {

        }

        class Urgent {

        }
    }

    class Election
    {

    }
}

package views {
    package nodes {
        class BuildingView
        {
        }

        class Budget
        {
        }

        class Satisfaction
        {
        }
    }
    package scenes 
    {
        class Start {
        }

        class Menu {
        }

        class GameOver {
        }
    }
}

RenovIUTApp ...> views
'controllers ..> models - déjà reflété par les liens de composition
'views ....> models
'views ...> controllers

Study *--> "*\n students" Student
Teaching *--> "*\n teachers" Teacher
Renovation *---> "*\n buildings" Building
Financing *--> "*\n funds" Fund

Student ..> StudentTableSQL
Teacher ..> TeacherTableSQL
Fund ..> FundTableSQL

Building --|> IT
Building --|> Communication
Building --|> Marketing
Building --|> Chemistry
Building --|> Engineering

Renovation -|> Urgent
Renovation -|> Planned

Election ...> Study
Election ...> Teaching
Election ...> Financing

BuildingView ...> Building
Budget ...> Financing
Satisfaction ...> school
Menu ...> management
GameOver ..> Election
@enduml
